name: Process-PSModule

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    branches:
      - main
    types:
      - closed
      - opened
      - reopened
      - synchronize
      - labeled

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  statuses: write
  pages: write
  id-token: write

jobs:
  Process-PSModule:
    uses: PSModule/Process-PSModule/.github/workflows/workflow.yml@0307c0d443c7daa295d10684017f1ac015efab38 # v6.1.12
    secrets:
      APIKey: ${{ secrets.APIKey }}
      TestData: >-
        {"variables":{"AZURE_TENANT_ID":"${{ vars.AZURE_TENANT_ID }}","AZURE_CLIENT_ID":"${{ vars.AZURE_CLIENT_ID }}","AZURE_SUBSCRIPTION_ID":"${{ vars.AZURE_SUBSCRIPTION_ID }}","AZURE_KEYVAULT_NAME":"${{ vars.AZURE_KEYVAULT_NAME }}","AZURE_KEYVAULT_KEY_NAME":"${{ vars.AZURE_KEYVAULT_KEY_NAME }}","AZURE_KEYVAULT_KEY_VERSION":"${{ vars.AZURE_KEYVAULT_KEY_VERSION }}"}}
